### ISSUE TITLE
0

### ISSUE THREAD

**Issue by MarilynPalmer** [skiprocks999/Dynamic-Electricity#1]
[crash-2021-12-10_19.47.32-server.txt](https://github.com/skiprocks999/Dynamic-Electricity/files/7692448/crash-2021-12-10_19.47.32-server.txt)
[latest.log](https://github.com/skiprocks999/Dynamic-Electricity/files/7692451/latest.log)
[debug.log](https://github.com/skiprocks999/Dynamic-Electricity/files/7692452/debug.log)

**Comment by skiprocks999** [comment]
huh that's a crash I didn't think could happen. It's fixed on the latest release for 1.18.
