### ISSUE TITLE
modpack crashing on startup

### ISSUE THREAD

**Issue by Meep1122131313** [skiprocks999/Dynamic-Electricity#11]
hello i have a custom modpack for 1.18.2 and whenever i add dynamic electricity it seems to crash with the error "could not reload shaders".
[latest.log](https://github.com/skiprocks999/Dynamic-Electricity/files/14502546/latest.log)
[debug.log](https://github.com/skiprocks999/Dynamic-Electricity/files/14502552/debug.log)
[crash-2024-03-05_23.12.53-client.txt](https://github.com/skiprocks999/Dynamic-Electricity/files/14502553/crash-2024-03-05_23.12.53-client.txt)

simply adding the dynamic electricity mod is what seems to cause the crashes

**Comment by skiprocks999** [comment]
Your jar is severely out of date.

**Comment by Meep1122131313** [comment]
Thanks I used the version of dynamic electricity on modrinth. Using the latest version on curseforge did the trick. Thanks!
