### ISSUE TITLE
1

### ISSUE THREAD

**Issue by MarilynPalmer** [skiprocks999/Dynamic-Electricity#2]
[crash-2021-12-11_09.20.08-client.txt](https://github.com/skiprocks999/Dynamic-Electricity/files/7696178/crash-2021-12-11_09.20.08-client.txt)
[debug.log](https://github.com/skiprocks999/Dynamic-Electricity/files/7696181/debug.log)
[latest.log](https://github.com/skiprocks999/Dynamic-Electricity/files/7696182/latest.log)

**Comment by skiprocks999** [comment]
fixed in latest release.
