### ISSUE TITLE
Crash while place any motor

### ISSUE THREAD

**Issue by tabr** [skiprocks999/Dynamic-Electricity#7]
Crash while place any motor:

 
item:dynamicelectricity:motordclv

item:dynamicelectricity:motordcmv

item:dynamicelectricity:motordchv

item:dynamicelectricity:motoraclv

item:dynamicelectricity:motoracmv

item:dynamicelectricity:motorachv

https://pastebin.com/uWxVEEQq

**Comment by skiprocks999** [comment]
I haven't had a chance to update dynamic yet to the new Electrodynamics formatting. I'll be doing that shortly
