### ISSUE TITLE
Lubricant Gel/Liquid

### ISSUE THREAD

**Issue by Codename-11** [skiprocks999/Dynamic-Electricity#8]
I'm having trouble finding the proper lubricant to use with the mod. When I search for it via JEI, Industrial Lubricant shows up in a Lead-Lined Canister (via Nuclear Science) and Reinforced Canister (via Electrodynamics). I as well have Mekanism installed, so using their fluid storage tanks I was able to extract the Lubricant, then with Mekanism pipes, pump said fluid into the bottom of a 120V AC motor. This completely fills the reservoir seemingly, however the "Generating" status cycles between red/green every second or so. Is this the intended behavior?

Please let me know if I'm missing something or if there is an issue currently. Thank you!

**Comment by skiprocks999** [comment]
If the status is cycling, it is most likely a power issue. If the reservoir is full, that is definitely the issue then.
